### ISSUE TITLE
Latest mitmproxy requires a newer version of glibc than is available in the repos

### ISSUE THREAD

**Issue by cooperq** [Hainish/RaspberryPi-Packet-Sniffer#1]
The latest version of mitmproxy in pip requires a higher version of glibc than is available in the pi repos. We should either pin it to a known working version of mitm proxy or have the script install mitmproxy from the repos as I did (this is also a decent workaround for anyone reading this. Just `sudo apt install mitmproxy`)

**Comment by Hainish** [comment]
This appears fixed after running on debian buster
